"""Type stubs for franken_networkx._fnx (Rust extension module)."""

from typing import Any, Iterator, Optional, Union

__version__: str

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class NetworkXError(Exception): ...
class NetworkXPointlessConcept(NetworkXError): ...
class NetworkXAlgorithmError(NetworkXError): ...
class NetworkXUnfeasible(NetworkXError): ...
class NetworkXNoPath(NetworkXUnfeasible): ...
class NetworkXUnbounded(NetworkXError): ...
class NetworkXNotImplemented(NetworkXError): ...
class NodeNotFound(NetworkXError): ...
class HasACycle(NetworkXError): ...
class PowerIterationFailedConvergence(NetworkXError): ...

# ---------------------------------------------------------------------------
# View objects
# ---------------------------------------------------------------------------

class NodeView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self, data: Union[bool, str, None] = None, default: Any = None
    ) -> "NodeView": ...

class EdgeView:
    def __len__(self) -> int: ...
    def __contains__(self, edge: tuple[Any, Any]) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, edge: tuple[Any, Any]) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self,
        data: Union[bool, str, None] = None,
        nbunch: Any = None,
        default: Any = None,
    ) -> Any: ...

class DegreeView:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[Any, int]]: ...
    def __getitem__(self, n: Any) -> int: ...
    def __bool__(self) -> bool: ...

class AdjacencyView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __iter__(self) -> Iterator: ...
    def __bool__(self) -> bool: ...

# ---------------------------------------------------------------------------
# DiGraph view objects
# ---------------------------------------------------------------------------

class DiNodeView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self, data: Union[bool, str, None] = None, default: Any = None
    ) -> "DiNodeView": ...

class DiEdgeView:
    def __len__(self) -> int: ...
    def __contains__(self, edge: tuple[Any, Any]) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, edge: tuple[Any, Any]) -> dict[str, Any]: ...
    def __bool__(self) -> bool: ...
    def __call__(
        self,
        data: Union[bool, str, None] = None,
        nbunch: Any = None,
        default: Any = None,
    ) -> Any: ...

class DiDegreeView:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[Any, int]]: ...
    def __getitem__(self, n: Any) -> int: ...
    def __bool__(self) -> bool: ...

class DiAdjacencyView:
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __iter__(self) -> Iterator: ...
    def __bool__(self) -> bool: ...

# ---------------------------------------------------------------------------
# Graph class
# ---------------------------------------------------------------------------

class Graph:
    graph: dict[str, Any]
    nodes: NodeView
    edges: EdgeView
    degree: DegreeView
    adj: AdjacencyView
    name: str

    def __init__(
        self, incoming_graph_data: Any = None, **attr: Any
    ) -> None: ...
    def is_directed(self) -> bool: ...
    def is_multigraph(self) -> bool: ...
    def number_of_nodes(self) -> int: ...
    def order(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def size(self, weight: Optional[str] = None) -> float: ...
    def add_node(self, n: Any, **attr: Any) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Any, **attr: Any) -> None: ...
    def remove_node(self, n: Any) -> None: ...
    def remove_nodes_from(self, nodes: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, **attr: Any) -> None: ...
    def add_edges_from(self, ebunch_to_add: Any, **attr: Any) -> None: ...
    def add_weighted_edges_from(
        self, ebunch_to_add: Any, weight: str = "weight"
    ) -> None: ...
    def remove_edge(self, u: Any, v: Any) -> None: ...
    def remove_edges_from(self, ebunch: Any) -> None: ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    def has_node(self, n: Any) -> bool: ...
    def has_edge(self, u: Any, v: Any) -> bool: ...
    def neighbors(self, n: Any) -> list[Any]: ...
    def adjacency(self) -> list[tuple[Any, list[Any]]]: ...
    def copy(self) -> "Graph": ...
    def subgraph(self, nodes: Any) -> "Graph": ...
    def edge_subgraph(self, edges: Any) -> "Graph": ...
    def to_undirected(self) -> "Graph": ...
    def to_directed(self) -> None: ...
    def update(
        self, edges: Any = None, nodes: Any = None
    ) -> None: ...
    def number_of_edges_between(
        self, u: Any = None, v: Any = None
    ) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "Graph": ...
    def __deepcopy__(self, memo: Any = None) -> "Graph": ...

# ---------------------------------------------------------------------------
# DiGraph class
# ---------------------------------------------------------------------------

class DiGraph:
    graph: dict[str, Any]
    nodes: DiNodeView
    edges: DiEdgeView
    degree: DiDegreeView
    in_degree: DiDegreeView
    out_degree: DiDegreeView
    adj: DiAdjacencyView
    succ: DiAdjacencyView
    pred: DiAdjacencyView
    name: str

    def __init__(
        self, incoming_graph_data: Any = None, **attr: Any
    ) -> None: ...
    def is_directed(self) -> bool: ...
    def is_multigraph(self) -> bool: ...
    def number_of_nodes(self) -> int: ...
    def order(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def size(self, weight: Optional[str] = None) -> float: ...
    def add_node(self, n: Any, **attr: Any) -> None: ...
    def add_nodes_from(self, nodes_for_adding: Any, **attr: Any) -> None: ...
    def remove_node(self, n: Any) -> None: ...
    def remove_nodes_from(self, nodes: Any) -> None: ...
    def add_edge(self, u: Any, v: Any, **attr: Any) -> None: ...
    def add_edges_from(self, ebunch_to_add: Any, **attr: Any) -> None: ...
    def add_weighted_edges_from(
        self, ebunch_to_add: Any, weight: str = "weight"
    ) -> None: ...
    def remove_edge(self, u: Any, v: Any) -> None: ...
    def remove_edges_from(self, ebunch: Any) -> None: ...
    def clear(self) -> None: ...
    def clear_edges(self) -> None: ...
    def has_node(self, n: Any) -> bool: ...
    def has_edge(self, u: Any, v: Any) -> bool: ...
    def neighbors(self, n: Any) -> list[Any]: ...
    def successors(self, n: Any) -> list[Any]: ...
    def predecessors(self, n: Any) -> list[Any]: ...
    def adjacency(self) -> list[tuple[Any, list[Any]]]: ...
    def reverse(self) -> "DiGraph": ...
    def copy(self) -> "DiGraph": ...
    def subgraph(self, nodes: Any) -> "DiGraph": ...
    def edge_subgraph(self, edges: Any) -> "DiGraph": ...
    def to_undirected(self) -> Graph: ...
    def to_directed(self) -> "DiGraph": ...
    def update(
        self, edges: Any = None, nodes: Any = None
    ) -> None: ...
    def number_of_edges_between(
        self, u: Any = None, v: Any = None
    ) -> int: ...
    def __len__(self) -> int: ...
    def __contains__(self, n: Any) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, n: Any) -> dict[Any, dict[str, Any]]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "DiGraph": ...
    def __deepcopy__(self, memo: Any = None) -> "DiGraph": ...

# ---------------------------------------------------------------------------
# Algorithm functions — shortest path
# ---------------------------------------------------------------------------

def shortest_path(
    g: Graph,
    source: Any = None,
    target: Any = None,
    weight: Optional[str] = None,
    method: str = "dijkstra",
) -> Any: ...

def shortest_path_length(
    g: Graph,
    source: Any,
    target: Any,
    weight: Optional[str] = None,
) -> Any: ...

def has_path(g: Graph, source: Any, target: Any) -> bool: ...

def average_shortest_path_length(
    g: Graph, weight: Optional[str] = None
) -> float: ...

def dijkstra_path(
    g: Graph, source: Any, target: Any, weight: str = "weight"
) -> list[Any]: ...

def bellman_ford_path(
    g: Graph, source: Any, target: Any, weight: str = "weight"
) -> list[Any]: ...

def multi_source_dijkstra(
    g: Graph, sources: Any, weight: str = "weight"
) -> tuple[dict[Any, float], dict[Any, list[Any]]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — connectivity
# ---------------------------------------------------------------------------

def is_connected(g: Graph) -> bool: ...
def connected_components(g: Graph) -> list[list[Any]]: ...
def number_connected_components(g: Graph) -> int: ...
def node_connectivity(g: Graph) -> int: ...
def minimum_node_cut(g: Graph) -> list[Any]: ...
def edge_connectivity(g: Graph, capacity: str = "capacity") -> float: ...
def articulation_points(g: Graph) -> list[Any]: ...
def bridges(g: Graph) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — centrality
# ---------------------------------------------------------------------------

def degree_centrality(g: Graph) -> dict[Any, float]: ...
def closeness_centrality(g: Graph) -> dict[Any, float]: ...
def harmonic_centrality(g: Graph) -> dict[Any, float]: ...
def katz_centrality(g: Graph) -> dict[Any, float]: ...
def betweenness_centrality(g: Graph) -> dict[Any, float]: ...
def edge_betweenness_centrality(g: Graph) -> dict[tuple[Any, Any], float]: ...
def eigenvector_centrality(g: Graph) -> dict[Any, float]: ...
def pagerank(g: Graph) -> dict[Any, float]: ...
def hits(g: Graph) -> tuple[dict[Any, float], dict[Any, float]]: ...
def average_neighbor_degree(g: Graph) -> dict[Any, float]: ...
def degree_assortativity_coefficient(g: Graph) -> float: ...
def voterank(g: Graph) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — clustering
# ---------------------------------------------------------------------------

def clustering(g: Graph) -> dict[Any, float]: ...
def average_clustering(g: Graph) -> float: ...
def transitivity(g: Graph) -> float: ...
def triangles(g: Graph) -> dict[Any, int]: ...
def square_clustering(g: Graph) -> dict[Any, float]: ...
def find_cliques(g: Graph) -> list[list[Any]]: ...
def graph_clique_number(g: Graph) -> int: ...

# ---------------------------------------------------------------------------
# Algorithm functions — matching
# ---------------------------------------------------------------------------

def maximal_matching(g: Graph) -> list[tuple[Any, Any]]: ...
def max_weight_matching(
    g: Graph, weight: str = "weight"
) -> list[tuple[Any, Any]]: ...
def min_weight_matching(
    g: Graph, weight: str = "weight"
) -> list[tuple[Any, Any]]: ...
def min_edge_cover(g: Graph) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — flow
# ---------------------------------------------------------------------------

def maximum_flow_value(
    g: Graph, source: Any, sink: Any, capacity: str = "capacity"
) -> float: ...
def minimum_cut_value(
    g: Graph, source: Any, sink: Any, capacity: str = "capacity"
) -> float: ...

# ---------------------------------------------------------------------------
# Algorithm functions — distance measures
# ---------------------------------------------------------------------------

def density(g: Graph) -> float: ...
def eccentricity(g: Graph) -> dict[Any, int]: ...
def diameter(g: Graph) -> int: ...
def radius(g: Graph) -> int: ...
def center(g: Graph) -> list[Any]: ...
def periphery(g: Graph) -> list[Any]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — tree, forest, bipartite, coloring, core
# ---------------------------------------------------------------------------

def is_tree(g: Graph) -> bool: ...
def is_forest(g: Graph) -> bool: ...
def is_bipartite(g: Graph) -> bool: ...
def bipartite_sets(g: Graph) -> tuple[list[Any], list[Any]]: ...
def greedy_color(g: Graph) -> dict[Any, int]: ...
def core_number(g: Graph) -> dict[Any, int]: ...
def minimum_spanning_tree(g: Graph, weight: str = "weight") -> Graph: ...

# ---------------------------------------------------------------------------
# Algorithm functions — Euler
# ---------------------------------------------------------------------------

def is_eulerian(g: Graph) -> bool: ...
def has_eulerian_path(g: Graph) -> bool: ...
def is_semieulerian(g: Graph) -> bool: ...
def eulerian_circuit(
    g: Graph, source: Any = None
) -> list[tuple[Any, Any]]: ...
def eulerian_path(
    g: Graph, source: Any = None
) -> list[tuple[Any, Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — paths and cycles
# ---------------------------------------------------------------------------

def all_simple_paths(
    g: Graph, source: Any, target: Any, cutoff: Optional[int] = None
) -> list[list[Any]]: ...
def cycle_basis(
    g: Graph, root: Any = None
) -> list[list[Any]]: ...

# ---------------------------------------------------------------------------
# Algorithm functions — efficiency
# ---------------------------------------------------------------------------

def global_efficiency(g: Graph) -> float: ...
def local_efficiency(g: Graph) -> float: ...

# ---------------------------------------------------------------------------
# Graph generators — classic
# ---------------------------------------------------------------------------

def empty_graph(n: int = 0) -> Graph: ...
def path_graph(n: int) -> Graph: ...
def cycle_graph(n: int) -> Graph: ...
def star_graph(n: int) -> Graph: ...
def complete_graph(n: int) -> Graph: ...

# ---------------------------------------------------------------------------
# Graph generators — random
# ---------------------------------------------------------------------------

def gnp_random_graph(n: int, p: float, seed: int) -> Graph: ...

# ---------------------------------------------------------------------------
# Read/write — graph I/O
# ---------------------------------------------------------------------------

from typing import IO, Any, Union
from os import PathLike

def read_edgelist(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_edgelist(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
def read_adjlist(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_adjlist(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
def node_link_data(g: Union[Graph, DiGraph]) -> dict[str, Any]: ...
def node_link_graph(data: dict[str, Any]) -> Graph: ...
def read_graphml(path: Union[str, PathLike, IO[str]]) -> Graph: ...
def write_graphml(g: Union[Graph, DiGraph], path: Union[str, PathLike, IO[str]]) -> None: ...
